-- Database: "USER_ACTIVITIES"

-- DROP DATABASE "USER_ACTIVITIES";

CREATE DATABASE USER_ACTIVITIES
    WITH OWNER = postgres
    ENCODING = 'UTF8'
    TABLESPACE = pg_default
    LC_COLLATE = 'Russian_Russia.1251'
    LC_CTYPE = 'Russian_Russia.1251'
    CONNECTION LIMIT = -1;


-- Table: public."T_USER"

-- DROP TABLE public."T_USER";

CREATE TABLE public.T_USER
(
    USER_ID   SERIAL         NOT NULL PRIMARY KEY,
    USER_NAME character varying(255) NOT NULL
)
    WITH (
        OIDS= FALSE
    );
ALTER TABLE public.T_USER
    OWNER TO postgres;


-- Table: public."T_USER_ACTIVITY_LOG"

-- DROP TABLE public."T_USER_ACTIVITY_LOG";

CREATE TABLE public.T_USER_ACTIVITY_LOG
(
    ID             SERIAL  NOT NULL PRIMARY KEY,
    USER_ID        integer NOT NULL REFERENCES public.T_USER (USER_ID),
    ACTIVITY_DATE  TIMESTAMP    NOT NULL,
    ACTIVITY_COUNT integer NOT NULL
)
    WITH (
        OIDS= FALSE
    );
ALTER TABLE public.T_USER_ACTIVITY_LOG
    OWNER TO postgres;


INSERT INTO public.T_USER (USER_NAME) VALUES ('test1');
INSERT INTO public.T_USER (USER_NAME) VALUES ('test2');
INSERT INTO public.T_USER (USER_NAME) VALUES ('test3');
INSERT INTO public.T_USER_ACTIVITY_LOG (USER_ID, ACTIVITY_DATE, ACTIVITY_COUNT) VALUES (1,'2019-06-22 19:10:25-07', 1);
INSERT INTO public.T_USER_ACTIVITY_LOG (USER_ID, ACTIVITY_DATE, ACTIVITY_COUNT) VALUES (1,'2019-06-22 19:11:26-07', 2);
INSERT INTO public.T_USER_ACTIVITY_LOG (USER_ID, ACTIVITY_DATE, ACTIVITY_COUNT) VALUES (1,'2019-06-22 19:12:27-07', 3);
INSERT INTO public.T_USER_ACTIVITY_LOG (USER_ID, ACTIVITY_DATE, ACTIVITY_COUNT) VALUES (1,'2019-07-22 19:10:25-07', 4);
INSERT INTO public.T_USER_ACTIVITY_LOG (USER_ID, ACTIVITY_DATE, ACTIVITY_COUNT) VALUES (1,'2019-07-22 19:10:26-07', 5);