spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/USER_ACTIVITIES
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  mvc:
    servlet.load-on-startup: 1
    throw-exception-if-no-handler-found: true
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  error.whitelabel.enabled: false

